// <auto-generated />
using System;
using FirstResources.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FirstResources.Web.Migrations.BusinessDB
{
    [DbContext(typeof(BusinessDBContext))]
    [Migration("20200903044802_PerubahanKolom_DataKaryawan2")]
    partial class PerubahanKolom_DataKaryawan2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FirstResources.Web.Data.Business.Agama", b =>
                {
                    b.Property<int>("AgamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NamaAgama")
                        .HasColumnType("text");

                    b.HasKey("AgamaId");

                    b.ToTable("Agama");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.DataKaryawan", b =>
                {
                    b.Property<int>("DataKaryawanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AgamaId")
                        .HasColumnType("integer");

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<int?>("DepartemenId")
                        .HasColumnType("integer");

                    b.Property<int?>("JabatanId")
                        .HasColumnType("integer");

                    b.Property<int?>("JenisKelaminId")
                        .HasColumnType("integer");

                    b.Property<string>("NIK")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DataKaryawanId");

                    b.HasIndex("AgamaId");

                    b.HasIndex("DepartemenId");

                    b.HasIndex("JabatanId");

                    b.HasIndex("JenisKelaminId");

                    b.ToTable("DataKaryawan");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Departemen", b =>
                {
                    b.Property<int>("DepartemenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("DepartemenId");

                    b.ToTable("Departemen");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Jabatan", b =>
                {
                    b.Property<int>("JabatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("JabatanId");

                    b.ToTable("Jabatan");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.JenisKelamin", b =>
                {
                    b.Property<int>("JenisKelaminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NamaJenisKelamin")
                        .HasColumnType("text");

                    b.HasKey("JenisKelaminId");

                    b.ToTable("JenisKelamin");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.DataKaryawan", b =>
                {
                    b.HasOne("FirstResources.Web.Data.Business.Agama", "Agama")
                        .WithMany("DataKaryawan")
                        .HasForeignKey("AgamaId");

                    b.HasOne("FirstResources.Web.Data.Business.Departemen", "Departemen")
                        .WithMany("DataKaryawan")
                        .HasForeignKey("DepartemenId");

                    b.HasOne("FirstResources.Web.Data.Business.Jabatan", "Jabatan")
                        .WithMany("DataKaryawan")
                        .HasForeignKey("JabatanId");

                    b.HasOne("FirstResources.Web.Data.Business.JenisKelamin", "JenisKelamin")
                        .WithMany("DataKaryawan")
                        .HasForeignKey("JenisKelaminId");
                });
#pragma warning restore 612, 618
        }
    }
}
