// <auto-generated />
using System;
using FirstResources.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FirstResources.Web.Migrations.BusinessDB
{
    [DbContext(typeof(BusinessDBContext))]
    [Migration("20200903022749_ColumnRemoval")]
    partial class ColumnRemoval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FirstResources.Web.Data.Business.Agama", b =>
                {
                    b.Property<int>("AgamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataKaryawanId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaAgama")
                        .HasColumnType("text");

                    b.HasKey("AgamaId");

                    b.HasIndex("DataKaryawanId");

                    b.ToTable("Agama");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.DataKaryawan", b =>
                {
                    b.Property<int>("DataKaryawanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("NIK")
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.Property<string>("TanggalLahir")
                        .HasColumnType("text");

                    b.HasKey("DataKaryawanId");

                    b.ToTable("DataKaryawan");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Departemen", b =>
                {
                    b.Property<int>("DepartemenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataKaryawanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("DepartemenId");

                    b.HasIndex("DataKaryawanId");

                    b.ToTable("Departemen");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Jabatan", b =>
                {
                    b.Property<int>("JabatanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataKaryawanId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .HasColumnType("text");

                    b.HasKey("JabatanId");

                    b.HasIndex("DataKaryawanId");

                    b.ToTable("Jabatan");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.JenisKelamin", b =>
                {
                    b.Property<int>("JenisKelaminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataKaryawanId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaJenisKelamin")
                        .HasColumnType("text");

                    b.HasKey("JenisKelaminId");

                    b.HasIndex("DataKaryawanId");

                    b.ToTable("JenisKelamin");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Agama", b =>
                {
                    b.HasOne("FirstResources.Web.Data.Business.DataKaryawan", "DataKaryawan")
                        .WithMany("Agama")
                        .HasForeignKey("DataKaryawanId");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Departemen", b =>
                {
                    b.HasOne("FirstResources.Web.Data.Business.DataKaryawan", "DataKaryawan")
                        .WithMany("Departemen")
                        .HasForeignKey("DataKaryawanId");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.Jabatan", b =>
                {
                    b.HasOne("FirstResources.Web.Data.Business.DataKaryawan", "DataKaryawan")
                        .WithMany("Jabatan")
                        .HasForeignKey("DataKaryawanId");
                });

            modelBuilder.Entity("FirstResources.Web.Data.Business.JenisKelamin", b =>
                {
                    b.HasOne("FirstResources.Web.Data.Business.DataKaryawan", "DataKaryawan")
                        .WithMany("JenisKelamin")
                        .HasForeignKey("DataKaryawanId");
                });
#pragma warning restore 612, 618
        }
    }
}
